#!/bin/sh
# requires:
#   awk (gawk, parse+process cpu info)
#   bc (bc, calculate cpu usage percentage)
set -eu

used()  { awk '/^cpu  / {print $1+$2+$3+$6+$7+$8+$9+$10}'    < /proc/stat; }
total() { awk '/^cpu  / {for(i=s=0;i<NF;) s+=$++i; print s}' < /proc/stat; }
display() {
  text=$(printf '%s %2d%%' "${ICON-}" "$1")
  printf '{"full_text":"%s","short_text":"%s","color":"%s"}\n' \
    "$text" "$text" "${foreground-#ffffff}"
}

old_used=$(used)
old_total=$(total)

while :; do
  used=$(used)
  total=$(total)

  display "$(echo "100 * ($used - $old_used) / ($total - $old_total)" | bc -s)"

  old_used=$used
  old_total=$total

  sleep "${UPDATE_INTERVAL-2}"
done
