#!/bin/sh
set -e

used()  { awk '/^cpu / {print $1+$2+$3+$6+$7+$8+$9+$10}'         < /proc/stat; }
total() { awk '/^cpu / {for(i=s=0;i<NF;) s+=$++i} END {print s}' < /proc/stat; }
display() {
  text=$(printf '%s %2.0f%%' "${ICON-}" "$1")
  printf '{"full_text":"%s","short_text":"%s","color":"%s"}\n' \
    "$text" "$text" "${foreground-#ffffff}"
}

old_used=$(used)
old_total=$(total)

while :; do
  used=$(used)
  total=$(total)

  display "$(awk "BEGIN {print 100 * ($used - $old_used) / ($total - $old_total)}")"

  old_used=$used
  old_total=$total

  sleep "${UPDATE_INTERVAL-2}"
done
