#!/bin/sh
# uses:
#   xgetres (xgetres, Xresources values)
set -eu

case ${BLOCK_INSTANCE-} in
  date)
    full_format=${DATE_FORMAT_FULL-%a, %b %d, %Y}
    short_format=${DATE_FORMAT_SHORT-%Y-%m-%d}
    color=${COLOR_ICON_DATE-$(xgetres i3.color6 2>/dev/null || echo '#55ffff')}
    icon=${ICON_DATE-}
    if [ -z "$icon" ]; then
      icon=
      [ "${markup-}" = pango ] && icon="<b>$icon</b>"
    fi
    ;;
  time)
    full_format=${TIME_FORMAT_FULL-%H:%M:%S}
    short_format=${TIME_FORMAT_SHORT-$full_format}
    color=${COLOR_ICON_TIME-$(xgetres i3.color6 2>/dev/null || echo '#55ffff')}
    icon=${ICON_TIME-}
    if [ -z "$icon" ]; then
      icon=
      [ "${markup-}" = pango ] && icon="<b>$icon</b>"
    fi
    ;;
  *) exit ;;
esac

[ "${markup-}" = pango ] && icon="<span color='$color'>$icon</span>"

echo "$icon $(date +"$full_format")"
echo "$icon $(date +"$short_format")"
