#!/bin/sh
set -e

[ "${markup-}" = pango ] && pango=true || pango=false
target=${BLOCK_INSTANCE-/home}

true()  { return 0; }
false() { ! true;   }

dfree() {
  fields=$1; shift
  df --output="$fields" "$@" "$target" | tail -n 1
}

color=${COLOR_ICON_DRIVE-${color6-#55ffff}}
icon=$ICON_DRIVE
if [ -z "$icon" ]; then
  icon=
  $pango && icon="<b>$icon</b>"
fi
$pango && icon="<span color='$color'>$icon</span>"

if [ ! -e "$target" ] || ! df "$target" >/dev/null; then
  echo "$icon $target ??"
  exit
fi

root=$(dfree target)
percent=$(awk "BEGIN {print 100 * $(dfree avail) / $(dfree size)}")
avail=$(dfree avail -B"${MEMORY_UNIT-GB}" | xargs printf '%s')

echo "$icon $avail $root"
echo "$icon $avail $root"
if [ "$percent" -lt "${CRITICAL_THRESHOLD-5}" ]; then
  echo "${COLOR_CRITICAL-${color1-#ff5555}}"
fi
