#!/bin/sh
# requires:
#   ip (iproute2, determine default route + device addr)
set -e

AF=${AF-inet6?}

iface=${BLOCK_INSTANCE-$(ip route | awk '/^default/ {print $5; exit}')}
# no default route
[ -n "$iface" ] || exit 0

case $iface in
  e*|t*) icon= ;;
    wl*) icon= ;;
    ww*) icon= ;;
esac
[ "${markup-}" = pango ] && icon="<b>$icon</b>"

# interface missing
if [ ! -d "/sys/class/net/$iface" ]; then
  echo "$icon $iface ??"
  echo "$icon"
  exit
fi

addr=$(ip addr show dev "$iface" | awk '/'"$AF"'/ {print $2; exit}')
addr=${addr%/*}

[ -z "$addr" ] && echo "$icon addr ??" || echo "$icon $addr"
echo "$icon"
if [ -z "$addr" ]; then
  echo "${color1-#800000}"
else
  echo "${color10-#55ff55}"
fi
