#!/bin/sh
# requires:
#   ip (iproute2, determine default route + device addr)
# uses:
#   xgetres (xgetres, retrieve X resource values)
set -eu

markup=${markup-}
AF=${AF-inet6?}

iface=${BLOCK_INSTANCE-$(ip route | awk '/^default/ {print $5; exit}')}
# no default route
[ -z "$iface" ] && exit

case $iface in
  en*|eth*) icon= ;;
  wl*) icon= ;;
  ww*) icon= ;;
esac
[ "$markup" = pango ] && icon="<b>$icon</b>"

# interface missing
if [ ! -d "/sys/class/net/$iface" ]; then
  echo "$icon $iface ??"
  echo "$icon"
  exit
fi

addr=$(ip addr show dev "$iface" | awk '/'"$AF"'/ {print $2; exit}')
addr=${addr%/*}

[ -z "$addr" ] && echo "$icon addr ??" || echo "$icon $addr"
echo "$icon"
if [ -z "$addr" ]; then
  xgetres i3.color1  || echo "#800000"
else
  xgetres i3.color10 || echo "#55ff55"
fi
