#!/bin/sh
# uses:
#   xgetres (xgetres, retrieve X resource values)
set -eu

markup=${markup-}
AF=${AF-inet6?}

iface=${BLOCK_INSTANCE-$(ip route | awk '/^default/ {print $5; exit}')}
# no default route
[ -z "$iface" ] && exit

case $iface in
  e*) icon= ;;
  w*) icon= ;;
esac
[ "$markup" = pango ] && icon="<b>$icon</b>"

# interface missing
if [ ! -d "/sys/class/net/$iface" ]; then
  if [ -n "$icon" ]; then
    echo "$icon"
    echo "$icon"
    xgetres i3.color9 || echo "#ff5555"
  fi
  exit
fi

addr=$(ip addr show dev "$iface" | awk '/'"$AF"'/ {print $2; exit}')
addr=${addr%/*}

echo "$icon $addr"
echo "$icon"
xgetres i3.color10 || echo "#55ff55"
