#!/bin/sh
# requires:
#   awk (gawk, fetch mem values+compute if under given threshold)
set -e

lo=${THRESHOLD_LOW-1}
memory=${MEMORY-Mem}
unit=${MEMORY_UNIT-giga}
icon=${ICON_MEMORY-}

case $memory in
  Mem|Swap) ;;
  *) echo "$icon $memory ??"; exit ;;
esac

case $unit in
  bytes|kilo|mega|giga|tera|peta|kibi|mebi|gibi|tebi|pebi) ;;
  *) echo "$icon $unit ??"; exit ;;
esac
case $unit in
  b*) hunit=B ;;
  k*) hunit=K ;;
  m*) hunit=M ;;
  g*) hunit=G ;;
  t*) hunit=T ;;
  p*) hunit=P ;;
esac
case $unit in *bi) hunit=${hunit}iB ;; esac

memory() {
  case $1 in
    total) col=2 ;;
    used)  col=3 ;;
    free)  col=4 ;;
    *) echo "$icon field $1 ??"; exit ;;
  esac
  shift
  free --"$unit" "$@" | awk "/^$memory:/ {print \$$col}"
}

used=$(memory used)

if [ "$used" -lt "$lo" ]; then
  [ "${markup-}" = pango ] && used="&lt;$lo" || used="<$lo"
  used=$used$hunit
else
  used=$(memory used -h)
fi

echo "$icon $used / $(memory total -h)"
echo "$icon $used"
