#!/bin/sh
# requires:
# - checkupdates (pacman-contrib)
# uses:
# - yay (yay)
set -e

while ! grep -q up /sys/class/net/*/operstate; do
  sleep "${BLOCK_INTERVAL-5}"
done

BLOCK_BUTTON=${BLOCK_BUTTON--1}
BUTTON_CHECK=${BUTTON_CHECK-1}
PACMAN=${PACMAN-pacman}

app_name=${0##*/}
nid_file=${XDG_RUNTIME_DIR-/tmp}/.$app_name.i3b.nid
[ "${markup-}" = pango ] && pango=true || pango=false
pkgs_max=${NOTIFICATION_PKGS_MAX-20}

true()  { return 0; }
false() { ! true;   }

ellipsize() {
  if [ ${#1} -gt "$2" ]; then
    printf '%.*s…\n' "$(($2 - 1))" "$1"
  else
    echo "$1"
  fi
}

prettify() {
  color_old=${COLOR_VERSION_OLD-${color9-#ff5555}}
  color_new=${COLOR_VERSION_NEW-${color10-#55ff55}}
  c=0
  while [ $c -le "$pkgs_max" ] && read -r pkg old _ new; do
    old=$(ellipsize "$old" 12)
    new=$(ellipsize "$new" 12)
    if $pango; then
      old="<span color='$color_old'>$old</span>"
      new="<span color='$color_new'>$new</span>"
    fi
    printf '%10s %-12s → %-12s\n' "$(ellipsize "$pkg" 10)" "$old" "$new"

    c=$((c + 1))
  done <<EOF
$@
EOF
}

notify() {
  notify-send.sh \
    --app-name "$app_name" \
    --icon update-manager \
    --expire-time 10000 \
    --replace-file "$nid_file" \
    "$@"
}

display() {
  icon=${ICON-}
  count=$1
  text=
  if $pango; then
    case $count in
       0) color=${ICON_COLOR_UPDATED-${color10-#55ff55}} ;;
      -*) color=${ICON_COLOR_FAILED-${color9-#ff5555}} ;;
       *) color=${ICON_COLOR_OUTDATED-${color11-#ffff55}} ;;
     esac
    icon="<span color='$color'>$icon</span>"
  fi
  [ "$count" -gt 0 ] && text=" $count"
  $pango && text="<b>$text</b>"

  echo "$icon$text"
  echo "$icon$text"
}

[ "$BLOCK_BUTTON" -eq "$BUTTON_CHECK" ] && notify=true || notify=false

$notify && notify "Checking for updates"
handle_error() {
  $notify && notify --icon dialog-error \
    "Something went wrong" \
    "Couldn't check if updates were available"
  display -1
  exit 0
}
trap handle_error USR1
pkgs=$({
  checkupdates || err=$?
  if [ ${err-0} -eq 1 ]; then
    kill -USR1 $$
    exit
  fi
  if [ "$PACMAN" != pacman ] && ! command -v "$PACMAN" >/dev/null; then
    kill -USR1 $$
    exit
  fi
  case $PACMAN in
    yay)
      set +e
      $PACMAN -Qua
      set -e
      ;;
  esac
})

count=$(printf "%s" "$pkgs" | wc -l)
[ -z "$pkgs" ] || count=$((count + 1))
if [ "$count" -eq 0 ]; then
  $notify && notify --icon checkmark --expire-time 3000 "System up-to-date"
elif $notify; then
  numupds="$count update"
  [ "$count" -eq 1 ] || numupds=${numupds}s
  if [ "$count" -gt "$pkgs_max" ]; then
    hidden="($((count - pkgs_max)) hidden)"
  fi
  notify --icon package "$numupds available $hidden" "$(prettify "$pkgs")"
fi

display "$count"
