#!/bin/zsh
source "$XDG_CONFIG_HOME/zsh/rc.d/opts"
source "$XDG_CONFIG_HOME/zsh/rc.d/keys"
source "$XDG_CONFIG_HOME/shell/interactive"

SAVEHIST=$HISTSIZE
export HISTFILE="$XDG_STATE_HOME/zsh/history"
mkdir -p "${HISTFILE%/*}"

# completion
autoload -Uz compinit
dump_file="$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"
mkdir -p "${dump_file%/*}"
if [[ -n $dump_file(#qN.mh+24) ]]; then
  compinit -d "$dump_file"
else
  compinit -Cd "$dump_file"
fi
unset dump_file

# bash completion
if autoload -U +X bashcompinit && bashcompinit; then
  find "$XDG_DATA_HOME/bash-completion/completions" \
    -type f \
    -exec source "{}" 2>/dev/null \;
fi

# lookup style
zstyle :compinstall filename '${ZDOTDIR:-$HOME}/.zshrc'
zstyle ':completion:*' cache-path '$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION'
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select
zstyle ':completion:*' rehash true
zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*:descriptions' format %U%B%d%b%u
zstyle ':completion:*:warnings' format '%BNo matches for: %d%b'

# load zsh/nearcolor if 24-bit colors aren't supported
case $COLOR_TERM in
  24bit|truecolor) ;;
  *) [ "${terminfo[colors]}" -eq 16777216 ] || zmodload zsh/nearcolor 2>/dev/null
esac

# prompt
PROMPT="[%F{cyan}%n%f@%F{cyan}%m%f %1~]%(?..%F{red})%(!.#.$)%f "

# plugins
for p in /usr/share/zsh/plugins/*; do source "$p/${p##*/}.zsh"; done 2>/dev/null
unset p

# functions
fp=/usr/share/zsh/site-functions
[ -d $fp ] && fpath=($fpath $fp)
unset fp

handle_usr1() { trap handle_usr1 USR1; rehash; }
trap handle_usr1 USR1
