#!/bin/zsh
# zmodload zsh/zprof
source "${XDG_CONFIG_HOME-$HOME/.config}/shell/rc"

SAVEHIST=$HISTSIZE
export HISTFILE="${XDG_STATE_HOME-$HOME/.local/state}/zsh/history"
mkdir -p "${HISTFILE%/*}"

source "${XDG_CONFIG_HOME-$HOME/.config}/zsh/rc.d/opts"
source "${XDG_CONFIG_HOME-$HOME/.config}/zsh/rc.d/keys"

# completion module
autoload -Uz compinit
cache_home="${XDG_CACHE_HOME-$HOME/.cache}/zsh"
mkdir -p "$cache_home"
for comp in "$cache_home"/zcompdump-$ZSH_VERSION(N.mh+24); do
  compinit -d "$cache_home/zcompdump-$ZSH_VERSION"
done; unset cache_home
compinit -C

# lookup style
zstyle :compinstall filename '${ZDOTDIR:-$HOME}/.zshrc'
zstyle ':completion:*' cache-path '${XDG_CACHE_HOME-$HOME/.cache}/zsh/zcompdump-$ZSH_VERSION'
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select
zstyle ':completion:*' rehash true
zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*:descriptions' format %U%B%d%b%u
zstyle ':completion:*:warnings' format '%BNo matches for: %d%b'

# load zsh/nearcolor if 24-bit colors aren't supported
case $COLOR_TERM in
  24bit|truecolor) ;;
  *) [ "${terminfo[colors]}" -eq 16777216 ] || zmodload zsh/nearcolor 2>/dev/null
esac

# prompt module
autoload -Uz promptinit && promptinit
# Go Bullet Trains
if [ -n "$GBT__HOME" ]; then
  PROMPT='$(gbt $?)'
  for prog (docker mysql screen ssh su sudo vagrant)
    typeset -f _$prog >/dev/null && compdef _$prog gbt_$prog=$prog
  unset prog
else
  prompt redhat
fi

# plugins
for p in /usr/share/zsh/plugins/*; do source "$p/${p##*/}.zsh"; done 2>/dev/null
unset p

# functions
fp=/usr/share/zsh/site-functions
[ -d $fp ] && fpath=($fp $fpath)
unset fp

handle_usr1() { trap handle_usr1 USR1; rehash; }
trap handle_usr1 USR1
# zprof
