#!/bin/sh
# requires:
# - jq
# uses:
# - notify-send

app_name=${0##*/}
should_notify=false

true()  { return 0; }
false() { ! true;   }

while [ $# -gt 0 ]; do
  case $1 in
    --notify) should_notify=true ;;
  esac
  shift
done

swaymsg input type:keyboard xkb_switch_layout next

if $should_notify; then
  notify-send \
    --expire-time 3000 \
    --app-name "$app_name" \
    --icon input-keyboard \
    "Keyboard Layout" \
    "$(swaymsg -t get_inputs|jq -r 'first(.[].xkb_active_layout_name|values)')"
fi

pkill -RTMIN+20 i3blocks
