#!/bin/sh

# disable ctrl+s as stopping shell
[ -t 0 ] && stty -ixon

export TERM="${TERM-xterm-256color}"

## history
HISTSIZE=10000

# gnupg
if command -v gpg-connect-agent >/dev/null; then
  GPG_TTY=$(tty)
  export GPG_TTY
  gpg-connect-agent updatestartuptty /bye >/dev/null 2>&1
fi

# less
for hl in lesspipe.sh lesspipe; do
  if cmd=$(command -v $hl); then
    export LESSOPEN="| $cmd %s 2>&-"
    break
  fi
done; unset cmd hl

## aliases
# config accessibility
config_alias() {
  if ! alias "$2" >/dev/null 2>&1; then
    base=$1; a=$2; shift 2
    for c in "$@"; do
      if [ -w "$base/$c" ]; then
        # shellcheck disable=SC2086,SC2139
        alias $a="\$EDITOR $base/$c"
        break
      fi
    done; unset c
    unset base a
  fi
}
home_config_alias() { config_alias "$HOME" "$@"; }
xdg_config_alias()  { config_alias "$XDG_CONFIG_HOME" "$@"; }

xdg_config_alias   alacrittycf alacritty/alacritty.yml
xdg_config_alias   batcf       bat/config
xdg_config_alias   dunstrc     dunst/dunstrc
xdg_config_alias   fcitxcf     fcitx/config
xdg_config_alias   fcitx5cf    fcitx5/config
xdg_config_alias   fontcf      fontconfig/fonts.conf
xdg_config_alias   footcf      foot/foot.ini
xdg_config_alias   gitcf       git/config
home_config_alias  gitcf       .gitconfig
xdg_config_alias   i3bcf       i3blocks/config
home_config_alias  i3bcf       .i3blocks.conf
xdg_config_alias   i3cf        i3/config
home_config_alias  i3cf        .i3/config
xdg_config_alias   inputrc     readline/inputrc
home_config_alias  inputrc     .inputrc
home_config_alias  juliarc     .julia/config/startup.jl
xdg_config_alias   kanshicf    kanshi/config
xdg_config_alias   makocf      mako/config
xdg_config_alias   muttrc      mutt/muttrc
home_config_alias  muttrc      .mutt/muttrc .muttrc
xdg_config_alias   mpvcf       mpv/mpv.conf
xdg_config_alias   neomuttrc   neomutt/neomuttrc
home_config_alias  neomuttrc   .neomutt/neomuttrc
xdg_config_alias   newsboatrc  newsboat/config
home_config_alias  newsboatrc  .newsboat/config
xdg_config_alias   npmcf       npm/config
xdg_config_alias   nvimrc      nvim/init.lua
xdg_config_alias   nvimrc      nvim/init.vim
xdg_config_alias   psqlrc      postgresql/psqlrc
xdg_config_alias   roficf      rofi/config
home_config_alias  sshcf       .ssh/config
xdg_config_alias   swaycf      sway/config
home_config_alias  swaycf      .sway/config
xdg_config_alias   swaylockcf  swaylock/config
home_config_alias  swaylockcf  .swaylock/config
xdg_config_alias   termitecf   termite/config
home_config_alias  vimrc       .vimrc
xdg_config_alias   zathurarc   zathura/zathurarc

unset -f config_alias home_config_alias xdg_config_alias

# shell
shell_conf_alias() {
  for f in env:environment rc:interactive login:login logout:logout; do
    dir="$XDG_CONFIG_HOME/$1"
    # shellcheck disable=SC2086,SC2139
    if [ -r "$dir/${f#*:}" ]; then
      alias .${2-$1}${f%:*}=". $dir/${f#*:}"
      [ -w "$dir/${f#*:}" ] && alias ${2-$1}${f%:*}="\$EDITOR $dir/${f#*:}"
    fi
  done; unset dir f
}

shell_conf_alias shell sh
shell_conf_alias bash
shell_conf_alias zsh

unset -f shell_conf_alias

alias cdtmp='cd $(mktemp -d)'

alias chgrp="chgrp --preserve-root"
alias chmod="chmod --preserve-root"
alias chown="chown --preserve-root"

alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

alias diff="diff --color"
alias dots='git --git-dir="$XDG_DATA_HOME/dotfiles" --work-tree="$HOME"'
alias g=git

alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

alias    l="ls -lFh"    #size,show type,human readable
alias   l.="ls -dF .*"  #hidden files
alias   lS="ls -1FSsh"  #dir sizes
alias   la="ls -lAFh"   #long list,show almost all,show type,human readable
alias   ll="ls -l"      #long list
alias   lr="ls -tRFh"   #sorted by date,recursive,show type,human readable
alias   ls="ls --color=auto"
alias   lt="ls -ltFh"   #long list,sorted by date,show type,human readable
alias  lrt="ls -1Fcrt"  #relative + types
alias lart="ls -1Fcart" #all relative + types

alias myip="curl -s https://ifconfig.me/ip"
alias netbeans='netbeans --userdir ${XDG_CONFIG_HOME-$HOME/.config}/netbeans --cachedir ${XDG_CACHE_HOME-$HOME/.cache}/netbeans'
alias n=nnn
alias nnn="nnn -d -e"
alias nv=nvim
alias o=open
alias open=xdg-open
alias rsync="rsync -azvhP" # archive compressed verbose human readable
alias sudo='sudo ' # alias expansion

alias tree="tree -C"

if command -v vim >/dev/null; then
  alias vi=vim
fi
alias  v=vi

alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'

alias xload='xrdb -load "$XDG_CONFIG_HOME/x11/xresources"'
alias xmerge='xrdb -merge "$XDG_CONFIG_HOME/x11/xresources"'

alias yt="youtube-dl -i4"
alias yta="yt -x"

# distro specific
alias pacman="pacman --color auto"
alias    yay="yay --color auto"

## functions
# shell
reload() { exec "${SHELL-sh}" "$@"; }

# xclip
if command -v xclip >/dev/null; then
  xcopy() {
    if [ ! -t 0 ]; then
      tmp=$(mktemp)
      # shellcheck disable=SC2064
      trap "rm -rf $tmp" EXIT HUP INT TERM
      while read -r line; do
        echo "$line" >> "$tmp"
      done
    fi

    input=${tmp-$1}
    unset tmp
    if command -v xdg-mime >/dev/null; then
      ft=$(xdg-mime query filetype "$input" 2>&-)
    else
      echo >&2 "Cannot infer MIME type for '$input', assuming plain text"
      ft=text/plain
    fi
    xclip -t "$ft" -selection clipboard -i "$input"
  }
  xpaste() { xclip -selection clipboard -o "$1" ; }
fi

# where were we?
CWD="$XDG_STATE_HOME/misc/cwd"
mkdir -p "${CWD%/*}"
__cd() {
  \cd "$@" || return
  pwd > "$CWD"
}
if [ -f "$CWD" ]; then
  cd "$(cat "$CWD")" 2>/dev/null || :
fi
alias cd=__cd

# shellcheck source=./rc.d/.keep
for file in "$XDG_CONFIG_HOME/shell/rc.d"/*.sh; do
  [ -r "$file" ] && . "$file"
done
