#!/bin/sh
## XDG Base Directory spec
# shellcheck disable=SC2174
[ -d "$XDG_RUNTIME_DIR" ] || mkdir -pm 0700 "$XDG_RUNTIME_DIR"

## umask
umask 0077

## ssh agent
eval "$(ssh-agent)" >/dev/null
export SSH_AUTH_SOCK

## graphic session
if [ -z "$DISPLAY" ]; then
  TTY=$(tty || echo "${XDG_VTNR--1}")
  TTY=${TTY#/dev/tty}
  # check for graphical env options
  case $TTY in
    1)
      command -v sway >/dev/null || return
      export MOZ_ENABLE_WAYLAND=1
      export XDG_SESSION_TYPE=wayland
      export XDG_CURRENT_DESKTOP=sway
      export _JAVA_AWT_WM_NONREPARENTING=1
      exec sway >/dev/null 2>&1
      ;;
    2)
      command -v gnome-shell >/dev/null || return
      export MOZ_ENABLE_WAYLAND=1
      export XDG_SESSION_TYPE=wayland
      export XDG_CURRENT_DESKTOP=gnome
      exec gnome-shell --wayland
      ;;
    3)
      command -v startx >/dev/null || return
      exec startx "$XINITRC" -- ":$TTY"
      ;;
    *) return ;;
  esac; unset TTY
fi
