#!/bin/sh
# shellcheck disable=SC1090
# based on lightdm's Xsession, logs stripped
# see https://git.archlinux.org/svntogit/packages.git/plain/trunk/Xsession?h=packages/lightdm

# Load resources
for file in /etc/X11/Xresources \
    "${XDG_CONFIG_HOME-$HOME/.config}/X11/xresources" \
    "$HOME/.Xresources"; do
  [ -f "$file" ] && xrdb -merge -I"${file%/*}" "$file"
done; unset file

# Load keymaps
for file in /etc/X11/Xkbmap "$HOME/.Xkbmap"; do
  [ -f "$file" ] && setxkbmap -config "$file" && XKB_IN_USE=yes
done; unset file

# Load xmodmap if not using XKB
if [ -z "$XKB_IN_USE" ]; then
  for file in /etc/X11/Xmodmap "$HOME/.Xmodmap"; do
    [ -f "$file" ] && xmodmap "$file"
  done; unset file
fi; unset XKB_IN_USE

# Source xinitrc.d scripts
for xinitrcd in /etc/X11/xinit/xinitrc.d \
    "${XDG_CONFIG_HOME-$HOME/.config}/X11/xresources" \
    "$HOME/.xinitrc.d"; do
  if [ -d "$xinitrcd" ]; then
    for script in "$xinitrcd"/*; do
      [ -x "$script" ] && [ ! -d "$script" ] && . "$script"
    done
  fi
done; unset xinitrcd

# Source user's .xsession

for file in "${XDG_CONFIG_HOME-$HOME/.config}/X11/xsession" \
    "$HOME/.Xsession"; do
  [ -x "$file" ] && [ ! -d "$file" ] && . "$file"
done; unset file

# run session
# optionally, first argument determines session. currently, defaults to i3
exec "${@:-i3}"
