#!/bin/sh
## environment setup
# browser
export BROWSER=firefox

# editor
for v in nvim vim vi; do
  command -v $v >&- && export EDITOR=$v && break
done; unset v
export VISUAL=$EDITOR
export SUDO_EDITOR=$EDITOR

# locale
DEFAULT_LANG=pt_PT.UTF-8
export LANG=en_US.UTF-8
export LC_ADDRESS=$DEFAULT_LANG
export LC_COLLATE=$DEFAULT_LANG
export LC_IDENTIFICATION=$DEFAULT_LANG
export LC_MONETARY=$DEFAULT_LANG
export LC_MEASUREMENT=$DEFAULT_LANG
export LC_PAPER=$DEFAULT_LANG
export LC_TELEPHONE=$DEFAULT_LANG
unset LC_ALL DEFAULT_LANG

# pager
for p in less more cat; do
  command -v $p >&- && export PAGER=$p && break
done; unset p
export LESS="-g -i -M -R -S -w -z-4"
# shellcheck disable=SC2155
{
export LESS_TERMCAP_mb=$(printf '\033[01;31m')
export LESS_TERMCAP_md=$(printf '\033[01;36m')
export LESS_TERMCAP_me=$(printf '\033[0m')
export LESS_TERMCAP_se=$(printf '\033[0m')
export LESS_TERMCAP_so=$(printf '\033[01;44;33m')
export LESS_TERMCAP_ue=$(printf '\033[0m')
export LESS_TERMCAP_us=$(printf '\033[01;32m')
}

# terminal setup
export TERMINAL=termite
export TERM=xterm-256color

# theme
export QT_QPA_PLATFORMTHEME=gtk3

# others
# nnn
export NNN_USER_EDITOR=1

## path configuration
local=$HOME/.local
mkdir -p "$local/scripts" && pathprepend "$local/scripts"
mkdir -p "$local/bin"     && pathprepend "$local/bin"
mkdir -p "$local/lib"     && pathprepend "$local/lib" LD_LIBRARY_PATH
mkdir -p "$local/include" && pathprepend "$local/include" CPATH
unset local

# launch X/Window Server
# shellcheck disable=SC1090
. "$HOME/.shell/xlogin"
