#!/bin/sh
# environment setup
export BROWSER=firefox

for v in nvim vim vi; do
  command -v $v >/dev/null && export EDITOR=$v && break
done; unset v
export VISUAL=$EDITOR
export SUDO_EDITOR=$EDITOR

export INPUT_METHOD=fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5

DEFAULT_LANG=pt_PT.UTF-8
export LANG=en_US.UTF-8
export LC_ADDRESS="$DEFAULT_LANG"
export LC_COLLATE="$DEFAULT_LANG"
export LC_IDENTIFICATION="$DEFAULT_LANG"
export LC_MONETARY="$DEFAULT_LANG"
export LC_MEASUREMENT="$DEFAULT_LANG"
export LC_PAPER="$DEFAULT_LANG"
export LC_TELEPHONE="$DEFAULT_LANG"
unset LC_ALL DEFAULT_LANG

NPROC=$(nproc || grep -c 'processor' < /proc/cpuinfo)
NPROC=${NPROC=1}
export NPROC

# shellcheck disable=SC2155
export JULIA_NUM_THREADS=$(( NPROC+2 ))

for p in less more cat; do
  command -v $p >/dev/null && export PAGER=$p && break
done; unset p
export LESS="-g -i -M -R -S -w -z-4"
# shellcheck disable=SC2155
{
export LESS_TERMCAP_mb=$(printf '\033[01;31m')
export LESS_TERMCAP_md=$(printf '\033[01;36m')
export LESS_TERMCAP_me=$(printf '\033[0m')
export LESS_TERMCAP_se=$(printf '\033[0m')
export LESS_TERMCAP_so=$(printf '\033[01;44;33m')
export LESS_TERMCAP_ue=$(printf '\033[0m')
export LESS_TERMCAP_us=$(printf '\033[01;32m')
}

# shellcheck disable=SC2155
export MAKEFLAGS=-j$(( NPROC+2 ))

export NNN_USER_EDITOR=1
export npm_config_prefix=~/.node_modules

export QT_QPA_PLATFORMTHEME=gtk3

export TERMINAL=termite
export TERM=xterm-256color


# path configuration
pathprepend "$npm_config_prefix"

local=$HOME/.local
mkdir -p "$local/bin"     && pathprepend "$local/bin"
mkdir -p "$local/lib"     && pathprepend "$local/lib" LD_LIBRARY_PATH
mkdir -p "$local/include" && pathprepend "$local/include" CPATH
unset local

## graphical environment
if [ -z "$DISPLAY" ]; then
  case ${XDG_VTNR--1} in
    1) exec with-env sway ;;
    2) exec startx -- ":1" ;;
  esac
fi
