#!/bin/sh
# environment setup
NPROC=$(nproc || grep -c 'processor' < /proc/cpuinfo)
export NPROC=${NPROC-2}

export BROWSER=firefox

for v in nvim vim vi; do
  command -v $v >/dev/null && export EDITOR=$v && break
done; unset v
export VISUAL=$EDITOR

export INPUT_METHOD=fcitx
export GTK_IM_MODULE=$INPUT_METHOD
export QT_IM_MODULE=$INPUT_METHOD
export XMODIFIERS=\@im=$INPUT_METHOD

export JULIA_NUM_THREADS=$(( NPROC+2 ))

lang=pt_PT.UTF-8
export LANG=en_US.UTF-8
export LC_ADDRESS=$lang
export LC_COLLATE=$lang
export LC_IDENTIFICATION=$lang
export LC_MONETARY=$lang
export LC_MEASUREMENT=$lang
export LC_PAPER=$lang
export LC_TELEPHONE=$lang
unset LC_ALL lang

export LESS="-igwMRS -z -4"
# shellcheck disable=SC2155
{
export LESS_TERMCAP_mb=$(printf '\033[01;31m')
export LESS_TERMCAP_md=$(printf '\033[01;36m')
export LESS_TERMCAP_me=$(printf '\033[0m')
export LESS_TERMCAP_se=$(printf '\033[0m')
export LESS_TERMCAP_so=$(printf '\033[01;44;33m')
export LESS_TERMCAP_ue=$(printf '\033[0m')
export LESS_TERMCAP_us=$(printf '\033[01;32m')
}

export MAKEFLAGS=-j$(( NPROC+2 ))

export NVM_DIR=${XDG_CONFIG_HOME-$HOME/.config}/nvm

for p in less more cat; do
  command -v $p >/dev/null && export PAGER=$p && break
done; unset p

export QT_QPA_PLATFORMTHEME=gtk3

export TERM=xterm-256color
export TERMINAL=alacritty


# path configuration
pathprepend "$HOME/.go/bin" # go
pathprepend "$HOME/.cargo/bin" # rust

pathprepend "$HOME/.local/bin"
pathprepend "$HOME/.local/lib" LD_LIBRARY_PATH
pathprepend "$HOME/.local/include" CPATH


# graphical environment
if [ -z "$DISPLAY" ]; then
  case ${XDG_VTNR--1} in
    1) command -v sway   >/dev/null && exec with-env sway 2>/dev/null  ;;
    2) command -v startx >/dev/null && exec startx -- ":1" ;;
  esac
fi
