#!/bin/sh
## graphical environment
# start x11 server (DISPLAY matches tty)
if [ -z "$DISPLAY" ] && [ "${XDG_VTNR--1}" -eq 1 ]; then
  command -v sx     >&- && exec sx
  command -v startx >&- && exec startx -- ":1"
fi
