# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,us(intl)
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =

    repeat_rate = 30
    repeat_delay = 350

    touchpad {
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
# synopsis: fingers, direction, action, options
gesture = 3, horizontal, workspace

