# https://wiki.hypr.land/Configuring/Variables/#general
general {
    layout = dwindle

    border_size = 2
    gaps_in = 7
    gaps_out = 15

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba($lavenderAlphaee)
    col.inactive_border = rgba($surface1Alphaaa)
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 10

    shadow {
        color = rgba($baseAlphaee)
    }
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}
