# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
windowrule = float on, pin on, match:class firefox, match:title Picture-in-Picture
windowrule = float on, match:class steam, match:title Friends List
windowrule = workspace 3, match:class firefox
windowrule = workspace 4, match:class discord
windowrule = workspace 4, match:class fluxer_app
windowrule = workspace 4, match:class whatsdesk
windowrule = workspace 4, match:class signal
