# This config is a DEPRECATED!
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

$bin = ~/.local/bin
$config = ~/.config/hypr
$scripts = $config/scripts

source = $config/themes/mocha.conf
source = $config/conf.d/*
