#!/bin/bash
# shellcheck disable=SC1091
source "$XDG_CONFIG_HOME/shell/interactive"

HISTCONTROL=ignoreboth

## Terminal options
# shell opts
shopt -s autocd
shopt -s extglob
shopt -s histappend

[ ! -s "$NVM_DIR/bash_completion" ] || source "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[ ! -f "$HOME/.travis/travis.sh" ] || source "$HOME/.travis/travis.sh"
