#!/bin/bash
# shellcheck disable=SC1091
source "$XDG_CONFIG_HOME/shell/rc"

HISTCONTROL=ignoreboth

## Terminal options
# shell opts
shopt -s autocd
shopt -s extglob
shopt -s histappend

[ -n "$GBT__HOME" ] && PS1='$(gbt $?)'
[ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"
