return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    dependencies = {
      "nvim-treesitter/nvim-treesitter-textobjects",
      "RRethy/nvim-treesitter-endwise",
      "windwp/nvim-ts-autotag",
    },
    opts = {
      autotag = { enable = true },
      endwise = { enable = true },
      highlight = { enable = true },
      indent = { enable = true },
      ensure_installed = {
        -- always
        "c",
        "lua",
        "vim",
        "vimdoc",
        "query",

        -- additional
        "bash",
        "bibtex",
        "cmake",
        "cpp",
        "css",
        "dockerfile",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "julia",
        "kotlin",
        "latex",
        "luadoc",
        "markdown",
        "markdown_inline",
        "python",
        "regex",
        "rust",
        "scheme",
        "scss",
        "sql",
        "toml",
        "tsx",
        "typescript",
        "yaml",
      },
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
}
